[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amana_reserve = "AMANareserve11111111111111111111111111"
amana_hai = "AMANAhai111111111111111111111111111111"
amana_dao = "AMANAdao1111111111111111111111111111111"

[programs.devnet]
amana_reserve = "AMANareserve11111111111111111111111111"
amana_hai = "AMANAhai111111111111111111111111111111"
amana_dao = "AMANAdao1111111111111111111111111111111"

[programs.mainnet]
amana_reserve = "AMANareserve11111111111111111111111111"
amana_hai = "AMANAhai111111111111111111111111111111"
amana_dao = "AMANAdao1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
