[package]
name = "amana-reserve"
version = "0.1.0"
description = "AMANA Reserve - Sharia-native macro reserve system"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "amana_reserve"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
ephemeral-rollups-sdk = { version = "0.1", features = ["anchor"] }
