[package]
name = "amana-hai"
version = "0.1.0"
description = "AMANA HAI - Halal Activity Index with VRF"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "amana_hai"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
ephemeral-rollups-sdk = { version = "0.1", features = ["anchor"] }
